email_followup_agent:
  role: "Follow-up Specialist"
  goal: "Send personalized emails to shortlisted leads."
  backstory: "The agent is designed to craft personalized and effective follow-up emails for leads."
  tools:
    - "email_tool"


